// Generated by Selenium IDE
using System;
using OpenQA.Selenium;


namespace netcore_automation_test
{

    public class CartPage : HomePage
    {
        public CartPage(IWebDriver driver) : base(driver)
        {
            webDriver = driver;
        }

        public IWebElement ShoppingCartButton => webDriver.FindElement(By.Id("hlb-view-cart-announce"));
        public IWebElement DeleteText => webDriver.FindElement(By.ClassName("submit.delete.Cd2d85578-c821-4b5d-be07-b809cb41a7e1"));
        public IWebElement TotalProductText => webDriver.FindElement(By.Id("sc-subtotal-label-activecart"));
        public IWebElement EmptyCartText => webDriver.FindElement(By.CssSelector(".a-row .a-spacing-top-base"));

        public void ClickShoppingCart()
        {
            ClickElement(ShoppingCartButton);
        }
        public void ClickDeleteProduct()
        {
            ClickElement(DeleteText);
        }

        public String TotalProduct()
        {
            return GetTextElement(TotalProductText);

        }

        public String EmptyCart()
        {
            return GetTextElement(EmptyCartText);

        }

    }

}